### ISSUE TITLE
Inconsistent padding above footer & missing gradient filter

### ISSUE THREAD

**Issue by izzycsy** [WavesHQ/quantum#581]
```
Ver: 0.15.0
Network: TestNet
Flow: DFC → ETH / ETH → DFC 
Description: inconsistent padding above footer & missing gradient filter
```

**Actual:** 
#### Desktop: 1440 x Hug
Padding: 112px

Gradient filter: missing
- Due to too much padding, unable to see gradient
- Or, gradient is missing
- Gradient should overlap <image>

#### Tablet: 768 x Hug
Padding: 112px

Gradient filter: missing

#### Mobile: 375 x Hug
On Web
Padding: >52px
- If green area is 32px, current padding would be >52px

Gradient filter: missing
- Gradient should overlap <image>

Background <image>: placement too low

#### On iOS
Padding: >52px
Gradient filter: missing

**Expected:** 
#### Desktop: 1440 x Hug
Padding: 80px
Gradient filter: Gradient should overlap <image>

#### Tablet: 768 x Hug
Padding: 48px
Gradient filter: present

#### Mobile: 375 x Hug
On Web
Padding: 52px
Gradient filter: present
Background image: present

#### On iOS
Padding: 52px
Gradient filter: present

`Desktop: 1440 x Hug`
<img width="1029" alt="230227 Quantum - 1440xHug - 80px padding1" src="https://user-images.githubusercontent.com/65014479/221526748-363ed7de-ceaf-4258-a4d6-322d5539c2ff.png">
<img width="1447" alt="230227 Quantum - 1440xHug - 80px padding2" src="https://user-images.githubusercontent.com/65014479/221526772-e16e9b38-955d-4351-98c6-86482a35b225.png">

`Tablet: 768 x Hug`
<img width="558" alt="230227 Quantum - 768xHug - 80px padding1" src="https://user-images.githubusercontent.com/65014479/221527005-74988ef0-63f0-4986-80fd-d28a6c34cea9.png">
<img width="763" alt="230227 Quantum - 768xHug - 80px padding2 2" src="https://user-images.githubusercontent.com/65014479/221527041-ddccf131-30ab-42b3-844d-0b8a5cb1801f.png">

`Mobile: 375 x Hug`
<img width="481" alt="230227 Quantum - 375xHug - 52px padding1" src="https://user-images.githubusercontent.com/65014479/221527104-1be605ef-a49c-45ff-8b53-e907b987258a.png">
<img width="805" alt="230227 Quantum - 375xHug - 52px padding2" src="https://user-images.githubusercontent.com/65014479/221527139-ee2fe12d-0906-4752-9783-c5fe92824e22.png">

**Comment by fullstackninja864** [comment]
@izzycsy issue is fixed in #574. Plz check.

**Comment by izzycsy** [comment]
@fullstackninja864 padding issue checked. On Mobile view, gradient is still missing, also some alignment issues. Kindly refer to ss. Thank you! 
```
Ver: 1.1.2
Network: MainNet
Flow: DFC → ETH / ETH → DFC 
Description: Missing gradient & align baseline
```
Changes to be made: 

1. Purple: Only on Android: `Connect wallet` missing kerning between characters
2. Blue: missing gradient
3. Yellow: Remove `.`
4. Orange: Align `ⓒ DeFiChain`
5. to be flush right
6. Pink: Align icons to be on same baseline


<img width="1263" alt="230308 Quantum - Gradient, flush right" src="https://user-images.githubusercontent.com/65014479/223631470-0a344b21-2f29-409c-83cd-7127f8600218.png">

**Comment by fullstackninja864** [comment]
1. Purple: Only on Android: Connect wallet missing kerning between characters => We are not using any letter spacing here, this might be because of native font style
2. Blue: missing gradient => its difficult to manage diff assets for diff screen size as BG image so i think its ok if we ignore this (good to have thing)
remaining will get fixed in [PR](https://github.com/WavesHQ/quantum/pull/722)
